title: sec fixture
plugins:
  - jekyll-sitemap
safe: false
include:
  - ../../../etc/passwd
  - .git
  - ../
theme: ../../../../etc
layouts_dir: ../../..
includes_dir: ../../..
plugins_dir: ../../..
source: /
destination: /tmp/pwn
